version: '3'
services:
  neo4j:
    # docker run --name testneo4j -p7474:7474 -p7687:7687 -d -v $HOME/neo4j/data:/data -v $HOME/neo4j/logs:/logs -v $HOME/neo4j/import:/var/lib/neo4j/import -v $HOME/neo4j/plugins:/plugins --env NEO4J_AUTH=neo4j/test neo4j:latest
    image: neo4j:4.0.4
    hostname: xcve-neo4j
    container_name: xcve-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    tmpfs:
      - /run
      - /data/tmp
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./csv2neo.cypher:/app/csv2neo.cypher
    environment:
      NEO4J_AUTH: neo4j/streams
      NEO4J_dbms_logs_debug_level: DEBUG
  web:
    build: .
    hostname: xcve-web
    container_name: xcve-web
    ports:
      - "8099:8099"
    depends_on:
      - neo4j
  fe:
    image: nginx:1.18
    hostname: xcve-fe
    container_name: xcve-fe
    network_mode: "host"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/logs:/var/log/nginx
      - ./public:/usr/share/nginx/html
    ports:
      - "8098:8098"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8098
    depends_on:
      - web
    command: [nginx-debug, '-g', 'daemon off;']