version: '3.4'
services:
  neo4j:
    # docker run --name testneo4j -p7474:7474 -p7687:7687 -d -v $HOME/neo4j/data:/data -v $HOME/neo4j/logs:/logs -v $HOME/neo4j/import:/var/lib/neo4j/import -v $HOME/neo4j/plugins:/plugins --env NEO4J_AUTH=neo4j/test neo4j:latest
    image: neo4j:4.0.4
    hostname: xcve-neo4j
    container_name: xcve-neo4j
    network_mode: "host"
    user: root
    privileged: true
    ports:
      - "7474:7474"
      - "7687:7687"
    tmpfs:
      - /run
      - /data/tmp
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/cypher:/app
    environment:
      NEO4J_AUTH: neo4j/streams
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_dbms_memory_heap_max__size: 6G
      NEO4J_kafka_group_id: xcve16
      NEO4J_kafka_zookeeper_connect: 117.50.109.103:2181
      NEO4J_kafka_bootstrap_servers: 117.50.109.103:9092
      NEO4J_kafka_auto_offset_reset: "earliest"
      NEO4J_streams_source_enabled: "false"
      NEO4J_streams_sink_enabled: "true"
      NEO4J_streams_sink_errors_log_enable: "true"
      NEO4J_streams_sink_errors_tolerance: "all"
      NEO4J_streams_sink_errors_include_messages: "true"
      NEO4J_streams_sink_topic_cypher_imageCVE: 
        "MERGE (i:Image {name: event.data.image_name, status: event.data.task_status, time:event.data.create_time})
        WITH event, i
        UNWIND event.data.vuln_data AS cve
        MERGE (c:CVE {name:cve.cve})
        MERGE (c)-[:EFFECT]->(i)"
  web:
    hostname: xcve-web
    container_name: xcve-web
    network_mode: "host"
    build:
      context: .
      network: host
    volumes:
      - ./app:/app
    ports:
      - "8099:8099"
    depends_on:
      - neo4j
  fe:
    build:
      context: .
      dockerfile: Dockerfile.fe
      network: host
    hostname: xcve-fe
    container_name: xcve-fe
    network_mode: "host"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/logs:/var/log/nginx
    ports:
      - "8098:8098"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8098
    depends_on:
      - web
    command: [nginx-debug, '-g', 'daemon off;']
