export const entryName = {
  CASE_KIND: "案件类型",
  COORG_NAME: "法院名称",
  CRIME_LOC: "犯罪地点",
  CRIME_NAME: "罪名",
  CRIME_PENALTY: "判罚",
  CRIME_TIME: "犯罪时间",
  DPER_ADDR: "现住址",
  DPER_BIRTHDATE: "被告人出生日期",
  DPER_CULTURE: "被告人文化水平",
  DPER_HOUSEHOLD: "被告人户籍所在地",
  DPER_ID: "被告人身份证号",
  DPER_JOB: "被告人职业",
  DPER_NAME: "被告人姓名",
  DPER_NATION: "被告人民族（国籍)",
  DPER_SEX: "性别",
  LAW_NAME: "法律法规名称",
  PIORG_NAME: "公安局名称",
  PRORG_NAME: "检察院名称",
  STHG_NAME: "赃物名称",
  STHG_VALUE: "赃物价值",
  VPER_NAME: "被害人姓名",
  WPER_NAME: "证人姓名",
  WTHG_NAME: "证物名称"
};
